Import the required libraries

In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests

import seaborn as sns

In [34]:
API_KEY = "2IEW11B1BXR32H7M"

In [48]:
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IBM&apikey=2IEW11B1BXR32H7M'

In [49]:
symbol = ['TD.TO', 'BNS.TO', 'RY.TO', 'CM.TO', 'NA.TO']

In [50]:
response = requests.get(url)
data = response.json()

In [60]:
response1 = response.json()
response1

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'IBM',
  '3. Last Refreshed': '2025-06-20',
  '4. Output Size': 'Compact',
  '5. Time Zone': 'US/Eastern'},
 'Time Series (Daily)': {'2025-06-20': {'1. open': '279.2800',
   '2. high': '284.1200',
   '3. low': '277.2000',
   '4. close': '280.9700',
   '5. volume': '7676962'},
  '2025-06-18': {'1. open': '285.0000',
   '2. high': '286.9100',
   '3. low': '282.9400',
   '4. close': '283.2100',
   '5. volume': '3534110'},
  '2025-06-17': {'1. open': '281.1500',
   '2. high': '284.7899',
   '3. low': '281.0001',
   '4. close': '283.0500',
   '5. volume': '3069556'},
  '2025-06-16': {'1. open': '279.3050',
   '2. high': '284.5000',
   '3. low': '278.6657',
   '4. close': '281.8300',
   '5. volume': '3685321'},
  '2025-06-13': {'1. open': '278.2050',
   '2. high': '279.8400',
   '3. low': '275.8300',
   '4. close': '277.2200',
   '5. volume': '3243824'},
  '2025-06-12': {'1. open': '281.5300',
   '2. high': '283.0600',
   '3. low': '279.8300',
   '4. close': '281.0300',
   '5. volume': '3418007'},
  '2025-06-11': {'1. open': '276.7000',
   '2. high': '281.7500',
   '3. low': '275.1100',
   '4. close': '281.5200',
   '5. volume': '4656034'},
  '2025-06-10': {'1. open': '273.1900',
   '2. high': '277.4700',
   '3. low': '272.5600',
   '4. close': '276.2400',
   '5. volume': '5163507'},
  '2025-06-09': {'1. open': '268.1000',
   '2. high': '273.4700',
   '3. low': '266.7100',
   '4. close': '272.0800',
   '5. volume': '4331464'},
  '2025-06-06': {'1. open': '267.9900',
   '2. high': '270.1700',
   '3. low': '267.5300',
   '4. close': '268.8700',
   '5. volume': '2495543'},
  '2025-06-05': {'1. open': '265.2000',
   '2. high': '267.5100',
   '3. low': '265.1000',
   '4. close': '266.8600',
   '5. volume': '2659478'},
  '2025-06-04': {'1. open': '264.9000',
   '2. high': '267.0000',
   '3. low': '264.7900',
   '4. close': '265.5200',
   '5. volume': '2588741'},
  '2025-06-03': {'1. open': '263.3500',
   '2. high': '265.5600',
   '3. low': '262.5800',
   '4. close': '265.2000',
   '5. volume': '2494922'},
  '2025-06-02': {'1. open': '257.8500',
   '2. high': '263.9760',
   '3. low': '257.2200',
   '4. close': '263.9000',
   '5. volume': '2831881'},
  '2025-05-30': {'1. open': '258.7500',
   '2. high': '260.1200',
   '3. low': '257.1000',
   '4. close': '259.0600',
   '5. volume': '9668923'},
  '2025-05-29': {'1. open': '260.7500',
   '2. high': '261.1300',
   '3. low': '256.7700',
   '4. close': '258.6900',
   '5. volume': '2295228'},
  '2025-05-28': {'1. open': '263.1600',
   '2. high': '265.0000',
   '3. low': '259.9400',
   '4. close': '260.2400',
   '5. volume': '2318437'},
  '2025-05-27': {'1. open': '261.0000',
   '2. high': '263.7869',
   '3. low': '259.6300',
   '4. close': '263.2300',
   '5. volume': '3284216'},
  '2025-05-23': {'1. open': '258.5800',
   '2. high': '259.8696',
   '3. low': '255.7900',
   '4. close': '258.6300',
   '5. volume': '2722721'},
  '2025-05-22': {'1. open': '260.7700',
   '2. high': '261.2711',
   '3. low': '257.9100',
   '4. close': '258.3700',
   '5. volume': '3091253'},
  '2025-05-21': {'1. open': '264.9700',
   '2. high': '265.6499',
   '3. low': '260.4100',
   '4. close': '260.8700',
   '5. volume': '3753904'},
  '2025-05-20': {'1. open': '267.4000',
   '2. high': '269.2800',
   '3. low': '265.6201',
   '4. close': '266.9500',
   '5. volume': '2437860'},
  '2025-05-19': {'1. open': '265.4500',
   '2. high': '269.1350',
   '3. low': '265.0800',
   '4. close': '268.4100',
   '5. volume': '3198903'},
  '2025-05-16': {'1. open': '266.3500',
   '2. high': '267.9800',
   '3. low': '264.5900',
   '4. close': '266.7600',
   '5. volume': '3817937'},
  '2025-05-15': {'1. open': '259.0100',
   '2. high': '267.4300',
   '3. low': '258.6100',
   '4. close': '266.6800',
   '5. volume': '4856276'},
  '2025-05-14': {'1. open': '257.6000',
   '2. high': '260.5500',
   '3. low': '256.2200',
   '4. close': '257.8200',
   '5. volume': '3635124'},
  '2025-05-13': {'1. open': '254.4300',
   '2. high': '259.5800',
   '3. low': '252.8800',
   '4. close': '258.5900',
   '5. volume': '3521389'},
  '2025-05-12': {'1. open': '252.5000',
   '2. high': '253.8100',
   '3. low': '244.6500',
   '4. close': '253.6900',
   '5. volume': '4609520'},
  '2025-05-09': {'1. open': '252.5100',
   '2. high': '253.0000',
   '3. low': '247.6400',
   '4. close': '249.2000',
   '5. volume': '2901346'},
  '2025-05-08': {'1. open': '255.0000',
   '2. high': '256.5200',
   '3. low': '253.2500',
   '4. close': '254.1400',
   '5. volume': '3637012'},
  '2025-05-07': {'1. open': '249.4500',
   '2. high': '254.4700',
   '3. low': '248.8320',
   '4. close': '253.3700',
   '5. volume': '3400001'},
  '2025-05-06': {'1. open': '247.7600',
   '2. high': '250.1900',
   '3. low': '246.1100',
   '4. close': '249.1200',
   '5. volume': '2900556'},
  '2025-05-05': {'1. open': '243.7400',
   '2. high': '249.8000',
   '3. low': '243.6400',
   '4. close': '249.1800',
   '5. volume': '4138168'},
  '2025-05-02': {'1. open': '243.1250',
   '2. high': '245.6900',
   '3. low': '241.3300',
   '4. close': '245.5500',
   '5. volume': '3731946'},
  '2025-05-01': {'1. open': '241.4400',
   '2. high': '242.3700',
   '3. low': '237.9450',
   '4. close': '239.6600',
   '5. volume': '4243294'},
  '2025-04-30': {'1. open': '236.7300',
   '2. high': '242.4700',
   '3. low': '234.3401',
   '4. close': '241.8200',
   '5. volume': '5142993'},
  '2025-04-29': {'1. open': '237.0000',
   '2. high': '239.9800',
   '3. low': '236.1400',
   '4. close': '239.3900',
   '5. volume': '3426508'},
  '2025-04-28': {'1. open': '232.8600',
   '2. high': '236.6300',
   '3. low': '232.0700',
   '4. close': '236.1600',
   '5. volume': '3653461'},
  '2025-04-25': {'1. open': '228.9500',
   '2. high': '233.3600',
   '3. low': '226.3200',
   '4. close': '232.4100',
   '5. volume': '6700068'},
  '2025-04-24': {'1. open': '231.1750',
   '2. high': '232.7800',
   '3. low': '224.4401',
   '4. close': '229.3300',
   '5. volume': '15428144'},
  '2025-04-23': {'1. open': '246.0000',
   '2. high': '249.3400',
   '3. low': '243.6600',
   '4. close': '245.4800',
   '5. volume': '7948259'},
  '2025-04-22': {'1. open': '238.5000',
   '2. high': '242.6400',
   '3. low': '238.0200',
   '4. close': '240.9000',
   '5. volume': '4232658'},
  '2025-04-21': {'1. open': '238.0650',
   '2. high': '240.8050',
   '3. low': '232.9300',
   '4. close': '236.2200',
   '5. volume': '4908923'},
  '2025-04-17': {'1. open': '239.6800',
   '2. high': '241.7750',
   '3. low': '237.4000',
   '4. close': '238.8100',
   '5. volume': '4635204'},
  '2025-04-16': {'1. open': '240.2800',
   '2. high': '243.2999',
   '3. low': '235.8900',
   '4. close': '238.5700',
   '5. volume': '4870299'},
  '2025-04-15': {'1. open': '239.5500',
   '2. high': '241.5300',
   '3. low': '238.2700',
   '4. close': '240.7000',
   '5. volume': '3363708'},
  '2025-04-14': {'1. open': '239.7700',
   '2. high': '241.7700',
   '3. low': '236.7300',
   '4. close': '239.0600',
   '5. volume': '3321717'},
  '2025-04-11': {'1. open': '229.7200',
   '2. high': '237.5800',
   '3. low': '227.5100',
   '4. close': '235.4800',
   '5. volume': '4325895'},
  '2025-04-10': {'1. open': '231.0000',
   '2. high': '232.5700',
   '3. low': '222.0200',
   '4. close': '229.5500',
   '5. volume': '5656108'},
  '2025-04-09': {'1. open': '217.1200',
   '2. high': '236.3000',
   '3. low': '215.1636',
   '4. close': '235.3100',
   '5. volume': '7302808'},
  '2025-04-08': {'1. open': '232.5600',
   '2. high': '233.0500',
   '3. low': '217.2800',
   '4. close': '221.0300',
   '5. volume': '6849996'},
  '2025-04-07': {'1. open': '219.2400',
   '2. high': '232.2900',
   '3. low': '214.5000',
   '4. close': '225.7800',
   '5. volume': '7797889'},
  '2025-04-04': {'1. open': '238.0000',
   '2. high': '240.1600',
   '3. low': '226.8800',
   '4. close': '227.4800',
   '5. volume': '7407096'},
  '2025-04-03': {'1. open': '242.7100',
   '2. high': '250.6100',
   '3. low': '242.5300',
   '4. close': '243.4900',
   '5. volume': '5309626'},
  '2025-04-02': {'1. open': '248.2200',
   '2. high': '252.7900',
   '3. low': '247.2300',
   '4. close': '249.9800',
   '5. volume': '4080832'},
  '2025-04-01': {'1. open': '248.0300',
   '2. high': '250.6200',
   '3. low': '243.4900',
   '4. close': '250.3400',
   '5. volume': '4413139'},
  '2025-03-31': {'1. open': '242.7400',
   '2. high': '250.8900',
   '3. low': '242.4900',
   '4. close': '248.6600',
   '5. volume': '6794972'},
  '2025-03-28': {'1. open': '246.2700',
   '2. high': '247.5700',
   '3. low': '242.0700',
   '4. close': '244.0000',
   '5. volume': '3125594'},
  '2025-03-27': {'1. open': '249.7100',
   '2. high': '250.3000',
   '3. low': '245.7250',
   '4. close': '246.2100',
   '5. volume': '2889328'},
  '2025-03-26': {'1. open': '251.2500',
   '2. high': '254.3200',
   '3. low': '249.5300',
   '4. close': '250.3400',
   '5. volume': '4452220'},
  '2025-03-25': {'1. open': '248.3600',
   '2. high': '250.9000',
   '3. low': '248.2000',
   '4. close': '249.9000',
   '5. volume': '3133809'},
  '2025-03-24': {'1. open': '247.3100',
   '2. high': '248.8200',
   '3. low': '245.9650',
   '4. close': '248.4500',
   '5. volume': '4753331'},
  '2025-03-21': {'1. open': '241.6900',
   '2. high': '245.2050',
   '3. low': '238.5000',
   '4. close': '243.8700',
   '5. volume': '9580084'},
  '2025-03-20': {'1. open': '244.2400',
   '2. high': '246.8000',
   '3. low': '237.2240',
   '4. close': '243.3200',
   '5. volume': '7026796'},
  '2025-03-19': {'1. open': '248.3300',
   '2. high': '253.6600',
   '3. low': '246.6400',
   '4. close': '252.2900',
   '5. volume': '3853598'},
  '2025-03-18': {'1. open': '252.5100',
   '2. high': '252.5700',
   '3. low': '245.1200',
   '4. close': '246.9500',
   '5. volume': '4172239'},
  '2025-03-17': {'1. open': '249.2500',
   '2. high': '254.6300',
   '3. low': '249.0000',
   '4. close': '252.9700',
   '5. volume': '3234149'},
  '2025-03-14': {'1. open': '242.7450',
   '2. high': '248.9499',
   '3. low': '241.6800',
   '4. close': '248.3500',
   '5. volume': '4045284'},
  '2025-03-13': {'1. open': '248.8000',
   '2. high': '249.2700',
   '3. low': '243.0400',
   '4. close': '245.8000',
   '5. volume': '3862416'},
  '2025-03-12': {'1. open': '250.3500',
   '2. high': '253.1273',
   '3. low': '245.5300',
   '4. close': '249.6300',
   '5. volume': '3849206'},
  '2025-03-11': {'1. open': '255.9900',
   '2. high': '256.7000',
   '3. low': '245.8600',
   '4. close': '248.9500',
   '5. volume': '5630570'},
  '2025-03-10': {'1. open': '261.5600',
   '2. high': '266.4500',
   '3. low': '254.7500',
   '4. close': '256.9000',
   '5. volume': '8126234'},
  '2025-03-07': {'1. open': '245.9500',
   '2. high': '261.9600',
   '3. low': '245.1823',
   '4. close': '261.5400',
   '5. volume': '6700184'},
  '2025-03-06': {'1. open': '249.7500',
   '2. high': '252.1000',
   '3. low': '246.8019',
   '4. close': '248.6900',
   '5. volume': '3254358'},
  '2025-03-05': {'1. open': '251.5800',
   '2. high': '252.7400',
   '3. low': '247.0146',
   '4. close': '251.3500',
   '5. volume': '4009813'},
  '2025-03-04': {'1. open': '248.7500',
   '2. high': '255.4800',
   '3. low': '248.1000',
   '4. close': '253.2100',
   '5. volume': '5342106'},
  '2025-03-03': {'1. open': '254.7350',
   '2. high': '255.9900',
   '3. low': '248.2450',
   '4. close': '250.1900',
   '5. volume': '2977699'},
  '2025-02-28': {'1. open': '250.8550',
   '2. high': '252.8099',
   '3. low': '246.5400',
   '4. close': '252.4400',
   '5. volume': '7988809'},
  '2025-02-27': {'1. open': '255.2200',
   '2. high': '257.6300',
   '3. low': '253.0500',
   '4. close': '253.2300',
   '5. volume': '3402234'},
  '2025-02-26': {'1. open': '258.1000',
   '2. high': '258.3250',
   '3. low': '254.4104',
   '4. close': '255.8400',
   '5. volume': '3460124'},
  '2025-02-25': {'1. open': '261.0800',
   '2. high': '263.4800',
   '3. low': '256.7700',
   '4. close': '257.7500',
   '5. volume': '6292487'},
  '2025-02-24': {'1. open': '261.5000',
   '2. high': '263.8450',
   '3. low': '259.5800',
   '4. close': '261.8700',
   '5. volume': '4398107'},
  '2025-02-21': {'1. open': '263.8450',
   '2. high': '264.8300',
   '3. low': '261.1000',
   '4. close': '261.4800',
   '5. volume': '5667874'},
  '2025-02-20': {'1. open': '263.6500',
   '2. high': '265.0900',
   '3. low': '262.1500',
   '4. close': '264.7400',
   '5. volume': '4884805'},
  '2025-02-19': {'1. open': '262.0000',
   '2. high': '264.3600',
   '3. low': '260.0900',
   '4. close': '264.3200',
   '5. volume': '3718678'},
  '2025-02-18': {'1. open': '261.9300',
   '2. high': '263.9650',
   '3. low': '259.8300',
   '4. close': '263.0700',
   '5. volume': '4262812'},
  '2025-02-14': {'1. open': '259.0000',
   '2. high': '261.9400',
   '3. low': '257.9100',
   '4. close': '261.2800',
   '5. volume': '3925277'},
  '2025-02-13': {'1. open': '255.6600',
   '2. high': '259.2800',
   '3. low': '254.4100',
   '4. close': '259.1900',
   '5. volume': '4531538'},
  '2025-02-12': {'1. open': '252.7200',
   '2. high': '256.4000',
   '3. low': '252.0200',
   '4. close': '255.8100',
   '5. volume': '3075308'},
  '2025-02-11': {'1. open': '251.1000',
   '2. high': '256.7500',
   '3. low': '250.5800',
   '4. close': '254.7000',
   '5. volume': '4801550'},
  '2025-02-10': {'1. open': '250.8600',
   '2. high': '251.9500',
   '3. low': '246.8700',
   '4. close': '249.2700',
   '5. volume': '3564400'},
  '2025-02-07': {'1. open': '255.2800',
   '2. high': '256.9300',
   '3. low': '252.0200',
   '4. close': '252.3400',
   '5. volume': '3370284'},
  '2025-02-06': {'1. open': '262.9800',
   '2. high': '263.3800',
   '3. low': '252.7300',
   '4. close': '253.4400',
   '5. volume': '6128293'},
  '2025-02-05': {'1. open': '265.7100',
   '2. high': '265.7200',
   '3. low': '261.1800',
   '4. close': '263.3000',
   '5. volume': '6165096'},
  '2025-02-04': {'1. open': '260.0000',
   '2. high': '265.2500',
   '3. low': '258.1233',
   '4. close': '264.4600',
   '5. volume': '6077652'},
  '2025-02-03': {'1. open': '252.4000',
   '2. high': '262.0600',
   '3. low': '251.8400',
   '4. close': '260.7300',
   '5. volume': '8408523'},
  '2025-01-31': {'1. open': '256.0500',
   '2. high': '257.2350',
   '3. low': '251.8900',
   '4. close': '255.7000',
   '5. volume': '7203519'},
  '2025-01-30': {'1. open': '250.0000',
   '2. high': '261.8000',
   '3. low': '247.0100',
   '4. close': '258.2700',
   '5. volume': '15381890'},
  '2025-01-29': {'1. open': '225.6200',
   '2. high': '229.4700',
   '3. low': '223.7300',
   '4. close': '228.6300',
   '5. volume': '7079804'},
  '2025-01-28': {'1. open': '224.3200',
   '2. high': '225.7700',
   '3. low': '221.7700',
   '4. close': '225.6600',
   '5. volume': '4485429'}}}

In [51]:
params = {
    'function': 'TIME_SERIES_DAILY_ADJUSTED',
    'symbol': symbol,
    'outputsize': 'compact',  # use 'full' for full history
    'apikey': API_KEY
}

In [52]:
timeseries = data.get('Time Series (Daily)', {})

In [53]:
df = pd.DataFrame.from_dict(timeseries, orient='index')

In [54]:
df = df.rename(columns=lambda x: x[3:].strip())  # Remove "1. ", "2. ", etc. from column names

In [55]:
df.index = pd.to_datetime(df.index)

In [56]:
df = df.sort_index()

In [57]:
df.columns = [col.split('. ')[1] if '. ' in col else col for col in df.columns]

In [58]:
df.head()

                open      high       low     close    volume
2025-01-28  224.3200  225.7700  221.7700  225.6600   4485429
2025-01-29  225.6200  229.4700  223.7300  228.6300   7079804
2025-01-30  250.0000  261.8000  247.0100  258.2700  15381890
2025-01-31  256.0500  257.2350  251.8900  255.7000   7203519
2025-02-03  252.4000  262.0600  251.8400  260.7300   8408523